repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.9
    hooks:
      # Run the linter.
      - id: ruff
        # args: [ --fix ] # will try to fix linting error on the spot
        # types_or: [ python, pyi, jupyter ] # lets you include notebooks in linting
      # Run the formatter.
      - id: ruff-format
        # types_or: [ python, pyi, jupyter ] # lets you include notebooks in formatting
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [--config=bandit.yml, -b, bandit_baseline.json]  # will run bandit on the entire project
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/fabasoad/pre-commit-snyk
    rev: v1.0.2
    hooks:
      - id: snyk-test
        args:
          - --snyk-args=--file=poetry.lock
          - --snyk-args=--package-manager=pip
          - --snyk-args=--fail-on=upgradable
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.11.0
    hooks:
      # Run the linter.
      - id: zizmor
